#!/bin/sh

#delete all files in a directory that contain no elements besides whitespace and the $format
#takes two arguments, the directory ($1) and a file that contains only maximum lines for a file to still be consiered "blank" ($2)
#if there is no second argument, remove blank files

folder="$1"
[ -z $folder ] && folder=~/doc/productivity/days

pattern="$2"
[ -z $pattern ] && pattern="to do|###|Calendar|got a sec?|^$"

#for now: only for td files

remove=""

for i in "$folder"/*; do
	#echo test
	#search for lines other than those that match to do, ###, or Calendar. if none are found, cat the file
	if [ -f "$i" ]; then	
		grep -Evq "$pattern" "$i" 2>/dev/null || remove="$remove $i"
	fi
done


while [ ! $i = yes ] && [ ! $i = no ] && [ ! $i = y ] && [ ! $i = n ]; do
	echo You are about to remove "$(echo $remove | wc -w)" files. Are you sure? [y/N]
	read i
done

if [ "$i" = yes ] || [ "$i" = y ]; then
	rm $remove
fi
