#!/bin/sh
jot_dir=/home/user/doc/jot/
rel_path=""
flags=""
dmenubrowse(){
	input="$(cd "$jot_dir$rel_path" && ls -p \
		| sed -e 's/.txt//' -e '/^\.$/d' -e '/#/d' -e '/~/d' -e 's|^\./||' | sort \
		| dmenu -p 'Enter a note')"

	if [ -n "$input" ]; then 
		[ "$input" = '..' ] && input='../' #for ease of use
		if [ -d "$jot_dir$rel_path$input" ]; then
			rel_path="$rel_path$input" && dmenubrowse 
		else
		    if  [ " $input" = "$(echo " $input" | grep -o ' \-.$')" ] ; then #if input is only a flag
			flags="$(echo " $input" | grep -o '\-.$')"
			dmenubrowse

		    elif echo "$input" | grep -q '\-.'; then #it has flags and more
			echo flag case 2
			flags="$flags$(echo "$input" | grep -o '\-.')"
			input="$(echo "$input" | sed 's/-. //')"
			jot "$flags" "$rel_path$input"
		    else
			if [ -n "$flags" ]; then
			    jot "$flags" "$rel_path$input"
			else
			    jot "$rel_path$input"
			fi
		    fi
		fi
	else
		exit 1
	fi
}
dmenubrowse

#to do: fix behavior with filenames ocntaining dashes
