#!/bin/sh

#caps lock to escape
setxkbmap -option caps:escape


#semicolon to up
xmodmap -e "keycode 47 = Up colon Up colon"
#apostrophe to Down, doublequotes (quotedbl) to apostrophe
xmodmap -e "keycode  48 = Down apostrophe Down apostrophe"



#tilde to semicolon; grave to double quote
xmodmap -e "keycode 49 = semicolon quotedbl semicolon quotedbl"

#1-0 swapped
xmodmap -e "keycode 10 = exclam 1 exclam 1"
xmodmap -e "keycode 11 = at 2 at 2"
xmodmap -e "keycode 12 = numbersign 3 numbersign 3"
xmodmap -e "keycode 13 = dollar 4 dollar 4"
xmodmap -e "keycode 14 = percent 5 percent 5"
xmodmap -e "keycode 15 = asciicircum 6 asciicircum 6"
xmodmap -e "keycode 16 = ampersand 7 ampersand 7"
xmodmap -e "keycode 17 = asterisk 8 asterisk 8"
xmodmap -e "keycode 18 = parenleft 9 parenleft 9"
xmodmap -e "keycode 19 = parenright 0 parenright 0"
#xmodmap -e "keycode 21 = equal plus equal plus"


#swap [ and ] with { and }
xmodmap -e "keycode  34 = braceleft bracketleft braceleft bracketleft"
xmodmap -e "keycode  35 = braceright bracketright braceright bracketright"

