#!/bin/dash

#ASSUMES NO OTHER KEYS WILL SHARE THESE BINDINGS

#binding_loc='^".scripts/clickbait"'

xpp_binding="	Shift + b:2"
normal_binding="	b:2"
file="$HOME/.xbindkeysrc"

normal(){
    #button 2 for menu
    sed -i "s/^$xpp_binding/$normal_binding/" "$file" &&
	killall xbindkeys &&
	xbindkeys --poll-rc

    xinput set-button-map 13 1 3 2

}

xpp(){
    #button 2 + shift for menu
    sed -i "s/^$normal_binding/$xpp_binding/" "$file" &&
	killall xbindkeys &&
	xbindkeys --poll-rc

    xinput set-button-map 13 1 2 3
}


toggle(){
#    echo toggling
    if grep -q "^$xpp_binding" "$file"; then
	normal
    else
	xpp
    fi

}

"$*" 2>/dev/null || toggle

