#!/bin/sh
if [ "$1" = "on" -o "$1" = "off" ]; then arg="$1"; else arg="toggle"; fi

if [ "$arg" = "on" ] || [ "$arg" = "toggle" -a -z "$(xrandr -q | grep VGA-1 | sed 's/VGA-1 //' | grep "[0-9]")" ] 
	then xrandr --verbose --output VGA-1 --auto --above LVDS-1 && MONITOR=VGA-1 polybar example & #echo switching on
	else xrandr --verbose --output VGA-1 --auto --off && MONITOR=LVDS-1 polybar example & #echo switching off
fi

.fehbg

xsetwacom set 10 MapToOutput LVDS-1 
xsetwacom set 13 MapToOutput LVDS-1 
xsetwacom set 14 MapToOutput LVDS-1 
xsetwacom set 15 MapToOutput LVDS-1
xsetwacom set 16 MapToOutput LVDS-1


#todo: parse xsetwacom --list devices for the above numbers as they appear to periodically change
