#!/bin/bash

selection="$(xsel | grep -v '^\ No newline at end of selection')"
if [ -z "$selection" ]; then exit; fi

options='man snarf feh clone locate td jot zathura vim mpv gvim surf firefox run'
rofi_options=""

#for i in $options; do echo $i; done
for i in $options; do rofi_options="$i\n$rofi_options"; done


#if selection is a file, open it in default application
if [ -f "$selection" ]; then xdg-open "$selection" & disown && exit; fi

#if selection is a directory, open it in a terminal
if [ -d "$selection" ]; then "$TERMINAL" -cd "$(cd $selection && pwd)" & disown && exit; fi


action="$(echo -e "$rofi_options" | rofi -dmenu)"
#echo "$action"
if [ "$action" = 'run' ]
then 
	$selection
elif [ "$action" = 'snarf' ] 
then 
	xsel -o | xsel -bi

elif [ "$action" = 'man' ] 
then 
	man -Tpdf "$selection" | zathura - #> ~/.scripts/output/man.pdf

elif [ "$action" = 'clone' ]
then
	(cd ~/.programs/ ; git clone "$selection")

else 
	$action $selection & disown
fi
