#!/bin/bash

shopt -s extglob

pomo_time_msg (){
    date_readable="$(echo "${1}" | sed 's/s/ seconds/' | sed 's/m/ minutes/' | sed 's/h/ hours/')"
    name=Timer && [ "${1}"  = "25m" ] && name=Pomodoro && killall dunst #silence notifications
    label="" && [ "${*:2}" != "$name done!" ] && label=" - ${*:2}"
    echo "$name set from $(date +%-I:%M\ %p) until $(date -d "$date_readable" +%-I:%M\ %p)$label"
    
    
    sleep "${1}" &&
	{ pgrep -xU "$UID" dunst || dunst & disown ; } &>/dev/null &&
	notify-send "${*:2}" >/dev/null &&
	mpv --force-window --loop-playlist=inf --really-quiet ~/.scripts/input/ringtone.webm &&
	pkill dunst && #kill the notification when mpv is closed
	dunst &>/dev/null & disown

}


case "$#" in
    0)
	pomo_time_msg 25m "Pomodoro done!" ;;

    1)
	case "$*" in
	    +([0-9]))
		pomo_time_msg "$*m" "Timer done!" ;;

	    +([0-9])[h,s,m])
		pomo_time_msg "$*" "Timer done!" ;;
			    

	    "cancel")
	 	killall sleep || exit 1;;
	

	    "stop")
		kill "$(ps aux | grep mpv | grep ringtone | tr -s [:blank:] | cut -d " " -f2)" 2>/dev/null || exit 1 ;;
	    

	    *)
		pomo_time_msg 25m "$*" ;;

	 esac
	
	;;


    *)
	case "$1" in
	    +([0-9]))
		pomo_time_msg "$1m" "${*:2}" ;;

	    +([0-9])[h,s,m])
		pomo_time_msg "$1"  "${*:2}" ;;

	    *)
		pomo_time_msg 25m "$*" 2>/dev/null || (echo "Timer length must precede message." && exit 1) ;;

	 esac

	;;
esac
