#!/bin/dash

if [ -f /home/user/Media/music/"$(mpc status | sed q)".m4a ]
	then ffmpeg -i /home/user/Media/music/"$(mpc status | sed q)".m4a /home/user/.scripts/output/cover.jpg -y 2>/dev/null
fi

	
if [ -f /home/user/Media/music/"$(mpc status | sed q)".mp3 ]
	then ffmpeg -i /home/user/Media/music/"$(mpc status | sed q)".mp3 /home/user/.scripts/output/cover.jpg -y 2>/dev/null
fi


if [ -f /home/user/Media/music/"$(mpc status | sed q)".flac ]
	then ffmpeg -i /home/user/Media/music/"$(mpc status | sed q)".flac /home/user/.scripts/output/cover.jpg -y 2>/dev/null
fi
