#!/bin/dash
file="$(find Media/music/ -wholename "*$(mpc status | sed q | sed 's/[]()[]/\\&/g' | sed 's|/|*|g')*" | sed q)"
[ -f "$file" ] && ffmpeg -i "$file" ~/.scripts/output/cover.jpg -y 2>/dev/null
