#!/bin/dash
file="$(find $MUSIC -wholename "*$(mpc status | sed q | sed 's/[]()[]/\\&/g' | sed 's|/|*|g')*" | sed q)"
if [ -f "$file" ]; then
    ffmpeg -i "$file" ~/.scripts/output/cover.jpg -y 2>/dev/null &&
	notify-send --icon="$HOME/.scripts/output/cover.jpg" "$(mpc status | sed q | sed 's/ - /\n/')"
    
fi
