#!/bin/dash

if [ -f ~/Media/music/"$(mpc status | sed q)".m4a ]
	then ffmpeg -i ~/Media/music/"$(mpc status | sed q)".m4a ~/.scripts/output/cover.jpg -y 2>/dev/null
fi

	
if [ -f ~/Media/music/"$(mpc status | sed q)".mp3 ]
	then ffmpeg -i ~/Media/music/"$(mpc status | sed q)".mp3 ~/.scripts/output/cover.jpg -y 2>/dev/null
fi


if [ -f ~/Media/music/"$(mpc status | sed q)".flac ]
	then ffmpeg -i ~/Media/music/"$(mpc status | sed q)".flac ~/.scripts/output/cover.jpg -y 2>/dev/null
fi
