#!/bin/bash

shopt -s extglob
dateformat='%m-%d-%y_%H:%M:%S'
prompt="Enter a name for your screenshot"

function promptname(){
    input="$(date +"$dateformat" | rofi -dmenu -p "$prompt" | tr -s '[:blank:]' '-')"
    echo $input | grep -E '\.(png|jpe?g)$' || echo $input.png
}

[[ "$1" = ?(-)?(-)@(clip?(board)|c?(opy)|y?(ank)) ]] && shift 1 &&
    result='| xclip -selection clipboard -t image/png' ||
	result="/tmp/screenshot.png"

eval maim  $* $result
[ -f "$result" ] && name=$(promptname) && mv "$result" "$PICTURE/grab/$name"
