#!/bin/sh

DATEFORMAT='%m-%d-%y_%H:%M:%S'
PROMPT="Enter a name for your screenshot"
tmp="$PICTURE/grab/tmp.png"

promptname(){
    input="$(echo "$(date +"$DATEFORMAT")" | rofi -dmenu -p "$PROMPT" | tr -s '[:blank:]' '_')"

    echo $input | grep -E '\.(png|jpe?g)$' || echo $input.png

}


scrot "$tmp" --line style=dash $*
 if [ -f "$tmp" ]; then
     name=$(promptname)
     mv "$tmp" "$PICTURE/grab/$name"
 fi
