#!/bin/dash

# uses bright to decrease brightness for eye adjustments
# takes as input:
#     - how much each step should change the brightness by
#     - at what interval (every how often)
#     - at what point the change should stop


usage(){
    echo "Usage:" && echo "strain-less increment interval stop"

}


current="$(xrandr --verbose | grep Brightness | tail -n 1 | cut -f2 -d '.')"
#flaw: if multiple monitors, only works for external

inc="$1"
#current="$current$(echo "$inc" | grep -o '^0*')"
freq="$2"
end="$3"

echo "$*" | grep -qi help && usage && exit 0
[ "$#" -eq 3 ] || (usage && exit 1)
[ -z "$end" ] && echo "Endpoint must be an integer between 0 and 100." && exit 2
[ -z "$current" ] && echo "Couldn't get current brightness." && exit 3
[ "$current" -gt "$end" ] || (echo "Endpoint must be lower than current brightness." && exit 4)


while [ "$current" -gt "$end" ]; do
    sleep "$freq"
    current=$(( current - inc ))
    bright 0.$current

done

