#!/bin/bash
log='~/.scripts/output/torrent.log'
rm $log
movies_dir='~/Media/videos/movies'
magnet_file='~/.scripts/input/magnets.txt'
cd $movies_dir
nordvpn connect >> $log && aria2c --seed-time=0 -i "$magnet_file" >> $log 
add autocomment all lines at end
sed -i 's/^[A-z]/#&/' "$magnet_file"
nordvpn disconnect >> $log
