#!/bin/dash
input="$(du -a "$VIDEO" | cut -f2- | grep -vE "\.vtt$|\.srt$|\.jpg$|\.png$|\.txt$|\.aria2$|\.part$|\.log$" | cut -d '/' -f6- | rofi -dmenu -i -l 30 -p 'Select a video')"
[ -n "$input" ] && mpvc "$VIDEO$input" -- --force-window #--input-file=~/.config/mpv/fifo

