#!/bin/sh

argcount=1
function help(){
    echo "Usage: $(basename $0) [pecent|up|+|down|-|mute|unmute|query|toggle]"
}
if [ $# -ne $argcount ]; then
    help && exit 1
fi



MAX=65537
MAX_PERCENT=150
factor=$((MAX / MAX_PERCENT))
step=5
current="$( pacmd list-sinks | grep 'volume' | tr -d '\t' | cut -f3 -d' ' | sed 1q )"

sink='@DEFAULT_SINK@'


case $1 in
    query)
	echo "$((current/factor))%"
	echo $current
	;;
    \+|up)
	"$(basename $0)" $(( current / factor + step))
	;;
    -|down)
	"$(basename $0)" $(( current / factor - step))
	;;
    mute|unmute|toggle)
	arg=$(echo $1 | sed -e 's/unmute/0/' -e 's/mute/1/')
	pactl set-sink-mute $sink $arg
	;;
    help|--help|-h)
	help
	;;
    *)
	arg="$(echo "$1" | tr -d '%')"
	if [ $arg -le $MAX_PERCENT ]; then
	    if [ $arg -ge 0 ]; then
		pacmd set-sink-volume $sink $(( factor * arg ))
	    else
		echo 'Percent must be greater than or equal to 0'
	    fi
	else
	    echo 'Percent must be less than or equal to 150'
	    exit 2
	fi	
	;;
esac
