#!/bin/sh

argcount=1
function help(){
    echo "Usage: $(basename $0) [pecent|up|+|down|-|mute|unmute|query|toggle]"
}
if [ $# -ne $argcount ]; then
    help && exit 1
fi

MAX_PERCENT=150 # currently unimplemented
step=2
sinks="$(pactl list sinks short | tr '[:blank:]' ' ' | cut -f2 -d' ')" # omit?

if [ $( echo "$sinks" | wc -l ) -gt 1 ]; then
    sink="$( echo "$sinks" | tail -n 1 )"
else
    sink='@DEFAULT_SINK@'
fi



case $1 in
    query)
	echo "$(( $(pamixer --get-volume) * 3 / 2 ))%$(pamixer --get-mute >/dev/null && echo ' (muted)')"
	;;
    \+|up)
	# "$(basename $0)" $(( current / factor + step))
	pamixer -i $step
	;;
    -|down)
	# "$(basename $0)" $(( current / factor - step))
	pamixer -d $step
	;;
    mute|unmute|toggle)
	arg=$(echo $1 | sed -e 's/unmute/0/' -e 's/mute/1/')
	pactl set-sink-mute $sink $arg # change to pamixer?
	;;
    help|--help|-h)
	help
	;;
    *)
	arg="$(echo "$1" | tr -d '%')"
	if [ $arg -le $MAX_PERCENT ]; then
	    if [ $arg -ge 0 ]; then
		# pacmd set-sink-volume $sink $(( factor * arg ))
		pamixer --set-volume $arg
	    else
		echo 'Percent must be greater than or equal to 0'
	    fi
	else
	    echo "Percent must be less than or equal to $MAX_PERCENT"
	    exit 2
	fi	
	;;
esac
