#!/bin/dash

# load the cover art of the currently playing song

# the file currently playing
file="$MUSIC/$( mpc current -f '%file%' )"
covers="$HOME/.scripts/output/covers/"
mkdir -p "$covers"
album_cover="$covers/$(mpc current -f '%artist% - %album%').png"
cover="$HOME/.scripts/output/cover.png"

if [ -f "$file" ]; then
    ffmpeg -i "$file" "$album_cover" -n 2>/dev/null
    cp "$album_cover" "$cover"
    pgrep dunst && notify-send --icon="$cover" "$(mpc current -f '%title%\n%artist%')"
    
fi



