#!/bin/sh

# If there is more than one argument, all arguments are searched (stopping at the first found). If the last argument is also not found, it is opened.

function wasRunFromTerminal(){
    # return successfully if run from terminal
    [ -t 0 -o -p /dev/stdin ] # maybe omit pipe part?
}


openInTerminal="$(echo $TERMINAL -c)"


function search(){
    xdotool search "$1" windowactivate %@
    }



function searchOrOpen(){
    # imperfect: does not detect `ncmpcpp`s, `vim`s opened from the command line
    case $# in
	1)
	    search "$1" ||  eval $1 &
	    ;;
	*)
	    case $1 in
		"-t")
		    shift 1
		    tui="$1"
		    shift 1
		    search "$tui" ||  searchOrOpen "$openInTerminal $tui" $*
		    ;;
		*)

		    search "$1" ||
			(shift 1 &&
			     searchOrOpen $*)
		    ;;
	    esac
    esac
}



searchOrOpen $*




