#!/bin/dash
#get id of root window
root=$(xdotool search --maxdepth 0 --class "") 

#get coordinates, screen, and window id of what's under the mouse
eval $(xdotool getmouselocation --shell)

#compare
[ "$WINDOW" = "$root" ]; exit $?
