#!/bin/bash

gap=16
bonus=4
screen_width=$(xrandr --prop | grep " connected" | tail -n 1 | sed 's/primary //' | cut -d ' '  -f3 | cut -d x -f1)
win_width=$(( "$screen_width" / 2 - "$gap" - ("$gap" / 2) - ($bonus / 2)))
#$1 is left or right

selection="$(xdotool getactivewindow)"
[ "$1" = select ] && selection="$(xdotool selectwindow)" && shift 1

if [ "$1" = 'left' ]; then
	xdotool windowsize $selection $win_width y windowmove $selection $gap y windowraise $selection #with gaps 
	exit
elif [ "$1" = 'right' ]; then
	xdotool windowsize $selection $win_width y windowmove $selection $(($win_width + $bonus + 2 * $gap)) y windowraise $selection #with gaps
	exit
fi

